batch_size: 128
config_path: D:\git\TranVT\exp\2024-03-24_20-09\config.yaml
dataset: swat
dataset_path: D:\git\TranVT\dataset\swat
epochs: 5
exp_path: D:\git\TranVT\exp\2024-03-24_20-09
logger: !!python/object/apply:logging.getLogger
- __main__
lr: 0.0001
model: TranVT
run_time: 2024-03-24_20-09
win_size: 10
